AWSTemplateFormatVersion: '2010-09-09'

Description: CRM System Network Stack

Parameters:

  ProjectName:
    Type: String
    Default: crm

  Environment:
    Type: String
    Default: dev

Resources:

  VPC:

    Type: AWS::EC2::VPC

    Properties:

      CidrBlock: 10.0.0.0/16

      EnableDnsSupport: true

      EnableDnsHostnames: true

      Tags:

        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-vpc

Outputs:

  VpcId:

    Description: VPC ID

    Value: !Ref VPC

    Export:

      Name: !Sub ${ProjectName}-${Environment}-VpcId
