AWSTemplateFormatVersion: '2010-09-09'

Description: CRM Compute Stack

Parameters:

  ProjectName:
    Type: String
    Default: crm

  Environment:
    Type: String
    Default: dev

Resources:

  EC2Role:

    Type: AWS::IAM::Role

    Properties:

      RoleName: !Sub ${ProjectName}-${Environment}-ec2-role

      AssumeRolePolicyDocument:

        Version: '2012-10-17'

        Statement:

          - Effect: Allow

            Principal:

              Service:

                - ec2.amazonaws.com

            Action:

              - sts:AssumeRole

      ManagedPolicyArns:

        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  EC2InstanceProfile:

    Type: AWS::IAM::InstanceProfile

    Properties:

      InstanceProfileName: !Sub ${ProjectName}-${Environment}-instance-profile

      Roles:

        - !Ref EC2Role

Outputs:

  EC2RoleArn:

    Value: !GetAtt EC2Role.Arn
